num1=int(input("enter first number"))
num2=int(input("enter second number"))
print("the sum is ",num1+num2)
print("the product is ",num1*num2)
print("the quotient is ",num1/num2)
print("the remainder is ",num1%num2)
print("the squre is ",num1**num2)